/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visao.outros.corporativo;

import com.mycompany.utilizades.BancoDeDadosMySql;
import com.mycompany.utilizades.Formularios;
import com.mycompany.visao.categoria.CadCategoria;
import com.mycompany.visao.categoria.ListCategoria;
import com.mycompany.visao.cidade.CadCidade;
import com.mycompany.visao.cidade.ListCidade;
import com.mycompany.visao.estado.CadEstado;
import com.mycompany.visao.estado.ListEstado;
import com.mycompany.visao.estado_civil.CadEstadoCivil;
import com.mycompany.visao.estado_civil.ListEstadoCivil;
import com.mycompany.visao.pais.CadPais;
import com.mycompany.visao.pais.ListPais;
import com.mycompany.visao.pedido.ListPedido;
import com.mycompany.visao.pessoa.CadPessoa;
import com.mycompany.visao.pessoa.ListPessoa;
import com.mycompany.visao.produto.CadProduto;
import com.mycompany.visao.produto.ListProduto;
import com.mycompany.visao.marca.CadMarca;
import com.mycompany.visao.marca.ListMarca;
import javax.swing.JOptionPane;

/**
 *
 * @author 10156
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        setExtendedState(MAXIMIZED_BOTH);
        
        if (!BancoDeDadosMySql.conectar()){
            JOptionPane.showMessageDialog(null, "Não foi possível conectar ao banco de dados. O sistema será finalizado.");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        miCadastroCategoria = new javax.swing.JMenuItem();
        miCadastroEstadoCivil = new javax.swing.JMenuItem();
        miCadastroMarca = new javax.swing.JMenuItem();
        miCadastroPais = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        miCadastroCidade = new javax.swing.JMenuItem();
        miCadastroEstado = new javax.swing.JMenuItem();
        miCadastroPessoa = new javax.swing.JMenuItem();
        miCadastroProduto = new javax.swing.JMenuItem();
        miConsultaEstadoCivil = new javax.swing.JMenu();
        miConsultaCategoria = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        miConsultaMarca = new javax.swing.JMenuItem();
        miConsultaPais = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miConsultaCidade = new javax.swing.JMenuItem();
        miConsultaEstado = new javax.swing.JMenuItem();
        miConsultaPessoa = new javax.swing.JMenuItem();
        miConsultaProduto = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miConsultaPedido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE VENDAS - PROGRAMADOR DE SISTEMAS 2023 | v. 1.0.0.3");

        mnCadastro.setText("Cadastros");

        miCadastroCategoria.setText("Categoria");
        miCadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroCategoriaActionPerformed(evt);
            }
        });
        mnCadastro.add(miCadastroCategoria);

        miCadastroEstadoCivil.setText("Estado civil");
        miCadastroEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroEstadoCivilActionPerformed(evt);
            }
        });
        mnCadastro.add(miCadastroEstadoCivil);

        miCadastroMarca.setText("Marca");
        miCadastroMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroMarcaActionPerformed(evt);
            }
        });
        mnCadastro.add(miCadastroMarca);

        miCadastroPais.setText("Pais");
        miCadastroPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroPaisActionPerformed(evt);
            }
        });
        mnCadastro.add(miCadastroPais);
        mnCadastro.add(jSeparator3);

        miCadastroCidade.setText("Cidade");
        miCadastroCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroCidadeActionPerformed(evt);
            }
        });
        mnCadastro.add(miCadastroCidade);

        miCadastroEstado.setText("Estado");
        miCadastroEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroEstadoActionPerformed(evt);
            }
        });
        mnCadastro.add(miCadastroEstado);

        miCadastroPessoa.setText("Pessoa");
        miCadastroPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroPessoaActionPerformed(evt);
            }
        });
        mnCadastro.add(miCadastroPessoa);

        miCadastroProduto.setText("Produto");
        miCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroProdutoActionPerformed(evt);
            }
        });
        mnCadastro.add(miCadastroProduto);

        menuBar.add(mnCadastro);

        miConsultaEstadoCivil.setText("Consultas");

        miConsultaCategoria.setText("Categoria");
        miConsultaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaCategoriaActionPerformed(evt);
            }
        });
        miConsultaEstadoCivil.add(miConsultaCategoria);

        jMenuItem2.setText("Estado civil");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        miConsultaEstadoCivil.add(jMenuItem2);

        miConsultaMarca.setText("Marca");
        miConsultaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaMarcaActionPerformed(evt);
            }
        });
        miConsultaEstadoCivil.add(miConsultaMarca);

        miConsultaPais.setText("Pais");
        miConsultaPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaPaisActionPerformed(evt);
            }
        });
        miConsultaEstadoCivil.add(miConsultaPais);
        miConsultaEstadoCivil.add(jSeparator1);

        miConsultaCidade.setText("Cidade");
        miConsultaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaCidadeActionPerformed(evt);
            }
        });
        miConsultaEstadoCivil.add(miConsultaCidade);

        miConsultaEstado.setText("Estado");
        miConsultaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaEstadoActionPerformed(evt);
            }
        });
        miConsultaEstadoCivil.add(miConsultaEstado);

        miConsultaPessoa.setText("Pessoa");
        miConsultaPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaPessoaActionPerformed(evt);
            }
        });
        miConsultaEstadoCivil.add(miConsultaPessoa);

        miConsultaProduto.setText("Produto");
        miConsultaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaProdutoActionPerformed(evt);
            }
        });
        miConsultaEstadoCivil.add(miConsultaProduto);
        miConsultaEstadoCivil.add(jSeparator2);

        miConsultaPedido.setText("Pedidos");
        miConsultaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaPedidoActionPerformed(evt);
            }
        });
        miConsultaEstadoCivil.add(miConsultaPedido);

        menuBar.add(miConsultaEstadoCivil);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroCategoriaActionPerformed
        if (Formularios.cadCategoria == null)
            Formularios.cadCategoria = new CadCategoria();
        
        Formularios.cadCategoria.setVisible(true);
    }//GEN-LAST:event_miCadastroCategoriaActionPerformed

    private void miConsultaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaCategoriaActionPerformed
        if (Formularios.listCategoria == null)
            Formularios.listCategoria = new ListCategoria();
        
        Formularios.listCategoria.setVisible(true);
    }//GEN-LAST:event_miConsultaCategoriaActionPerformed

    private void miCadastroCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroCidadeActionPerformed
        if (Formularios.cadCidade == null)
            Formularios.cadCidade = new CadCidade();
        
        Formularios.cadCidade.setVisible(true);
    }//GEN-LAST:event_miCadastroCidadeActionPerformed

    private void miConsultaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaCidadeActionPerformed
        if (Formularios.listCidade == null)
            Formularios.listCidade = new ListCidade();
        
        Formularios.listCidade.setVisible(true);
    }//GEN-LAST:event_miConsultaCidadeActionPerformed

    private void miCadastroPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroPaisActionPerformed
        if (Formularios.cadPais == null)
            Formularios.cadPais = new CadPais();
        
        Formularios.cadPais.setVisible(true);
    }//GEN-LAST:event_miCadastroPaisActionPerformed

    private void miConsultaPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaPaisActionPerformed
        if (Formularios.listPais == null)
            Formularios.listPais = new ListPais();
        
        Formularios.listPais.setVisible(true);
    }//GEN-LAST:event_miConsultaPaisActionPerformed

    private void miCadastroEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroEstadoActionPerformed
        if (Formularios.cadEstado == null)
            Formularios.cadEstado = new CadEstado();
        
        Formularios.cadEstado.setVisible(true);
    }//GEN-LAST:event_miCadastroEstadoActionPerformed

    private void miConsultaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaEstadoActionPerformed
        if (Formularios.listEstado == null)
            Formularios.listEstado = new ListEstado();
        
        Formularios.listEstado.setVisible(true);
    }//GEN-LAST:event_miConsultaEstadoActionPerformed

    private void miCadastroPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroPessoaActionPerformed
        if (Formularios.cadPessoa == null)
            Formularios.cadPessoa = new CadPessoa();
        
        Formularios.cadPessoa.setVisible(true);
    }//GEN-LAST:event_miCadastroPessoaActionPerformed

    private void miConsultaPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaPessoaActionPerformed
        if (Formularios.listPessoa == null)
            Formularios.listPessoa = new ListPessoa();
        
        Formularios.listPessoa.setVisible(true);
    }//GEN-LAST:event_miConsultaPessoaActionPerformed

    private void miCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroProdutoActionPerformed
        if (Formularios.cadProduto == null)
            Formularios.cadProduto = new CadProduto();
        
        Formularios.cadProduto.setVisible(true);
    }//GEN-LAST:event_miCadastroProdutoActionPerformed

    private void miConsultaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaProdutoActionPerformed
        if (Formularios.listProduto == null)
            Formularios.listProduto = new ListProduto();
        
        Formularios.listProduto.setVisible(true);
    }//GEN-LAST:event_miConsultaProdutoActionPerformed

    private void miCadastroMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroMarcaActionPerformed
        if (Formularios.cadMarca == null)
            Formularios.cadMarca = new CadMarca();
        
        Formularios.cadMarca.setVisible(true);
    }//GEN-LAST:event_miCadastroMarcaActionPerformed

    private void miConsultaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaMarcaActionPerformed
        if (Formularios.listMarca == null)
            Formularios.listMarca = new ListMarca();
        
        Formularios.listMarca.setVisible(true);
    }//GEN-LAST:event_miConsultaMarcaActionPerformed

    private void miCadastroEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroEstadoCivilActionPerformed
        if (Formularios.cadEstadoCivil == null)
            Formularios.cadEstadoCivil = new CadEstadoCivil();
        
        Formularios.cadEstadoCivil.setVisible(true);
    }//GEN-LAST:event_miCadastroEstadoCivilActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (Formularios.listEstadoCivil == null)
            Formularios.listEstadoCivil = new ListEstadoCivil();
        
        Formularios.listEstadoCivil.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void miConsultaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaPedidoActionPerformed
        if (Formularios.listPedido == null)
            Formularios.listPedido = new ListPedido();
        
        Formularios.listPedido.setVisible(true);
    }//GEN-LAST:event_miConsultaPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* CreatemiConsultaProduto and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miCadastroCategoria;
    private javax.swing.JMenuItem miCadastroCidade;
    private javax.swing.JMenuItem miCadastroEstado;
    private javax.swing.JMenuItem miCadastroEstadoCivil;
    private javax.swing.JMenuItem miCadastroMarca;
    private javax.swing.JMenuItem miCadastroPais;
    private javax.swing.JMenuItem miCadastroPessoa;
    private javax.swing.JMenuItem miCadastroProduto;
    private javax.swing.JMenuItem miConsultaCategoria;
    private javax.swing.JMenuItem miConsultaCidade;
    private javax.swing.JMenuItem miConsultaEstado;
    private javax.swing.JMenu miConsultaEstadoCivil;
    private javax.swing.JMenuItem miConsultaMarca;
    private javax.swing.JMenuItem miConsultaPais;
    private javax.swing.JMenuItem miConsultaPedido;
    private javax.swing.JMenuItem miConsultaPessoa;
    private javax.swing.JMenuItem miConsultaProduto;
    private javax.swing.JMenu mnCadastro;
    // End of variables declaration//GEN-END:variables
}
